### ISSUE TITLE
TypeError: Cannot call method “getThreads” of null

### ISSUE THREAD

**Issue by klppl** [hallzy/tv-show-notification#6]
Hi,

tried running this but I got the error mentioned in subject.

See screenshot.
![2017-04-27 14_21_50-tvshow tracker](https://cloud.githubusercontent.com/assets/2523049/25483150/f0155f64-2b54-11e7-8c9f-71c996b7c982.png)

**Comment by hallzy** [comment]
Thanks for the issue. I believe the issue is that you have not created the label yet for the feature it was looking for. That is fine as the feature is optional to use anyways which is the one where you can add tv shows to your sheet by emailing yourself with a specific email form (more about that in the readme).

It is fixed now (if the label is not created, it will just ignore this part now). I will push soon

**Comment by hallzy** [comment]
Just confirm for me that it is resolved now and I can close the issue

**Comment by klppl** [comment]
Now it works, thank you :)
